### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by CorwinDev** [Xeonpanel/Panel#2]
![image](https://user-images.githubusercontent.com/88144943/178519049-3b74b622-375a-40f3-954c-a927117e8f3b.png)

You get a error while downloading this source code.

**Comment by Boomba2022** [comment]
Shouldn't matter as you will use it on linux, to my knowledge linux doesn't really have virus detection.

**Comment by CorwinDev** [comment]
For development and testing it’s better that virus is removed :)

**Comment by Snikkertjuh** [comment]
Removed node_modules [https://github.com/Xeonpanel/Panel/commit/b97f9647c43e67c6e092417656720fa582511966](https://github.com/Xeonpanel/Panel/commit/b97f9647c43e67c6e092417656720fa582511966)
